kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Values.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  revisionHistoryLimit: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app_name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app_name: {{ .Chart.Name }}
        app_version: {{ .Values.image.tag | quote }}
        helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.ports.targetPort }}
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 10
          httpGet:
            path: "/greeting"
            port: {{ .Values.ports.targetPort  }}
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: "/greeting"
            port: {{ .Values.ports.targetPort  }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
